// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace LoadDwh.Models.Models;

public partial class DbOrderContext : DbContext
{
    public DbOrderContext(DbContextOptions<DbOrderContext> options)
        : base(options)
    {
    }

    public virtual DbSet<FactSale> FactSales { get; set; }

    public virtual DbSet<FactSupportedCustomer> FactSupportedCustomers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<FactSale>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__FactSale__C3905BAF075EF53E");

            entity.HasIndex(e => e.CustomerId, "IX_FactSales_CustomerID");

            entity.HasIndex(e => e.DateId, "IX_FactSales_DateID");

            entity.HasIndex(e => e.EmployeeId, "IX_FactSales_EmployeeID");

            entity.HasIndex(e => e.ProductId, "IX_FactSales_ProductID");

            entity.HasIndex(e => e.ShipperId, "IX_FactSales_ShipperID");

            entity.Property(e => e.OrderId)
                .ValueGeneratedNever()
                .HasColumnName("OrderID");
            entity.Property(e => e.Country)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CustomerId)
                .HasMaxLength(5)
                .IsFixedLength()
                .HasColumnName("CustomerID");
            entity.Property(e => e.DateId).HasColumnName("DateID");
            entity.Property(e => e.EmployeeId).HasColumnName("EmployeeID");
            entity.Property(e => e.ProductId).HasColumnName("ProductID");
            entity.Property(e => e.ShipperId).HasColumnName("ShipperID");
            entity.Property(e => e.TotalSales).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<FactSupportedCustomer>(entity =>
        {
            entity.HasKey(e => e.SupportedCustomersId).HasName("PK__FactSupp__37912749AAD1EBAC");

            entity.Property(e => e.SupportedCustomersId).ValueGeneratedNever();
            entity.Property(e => e.EmployeerName)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}