// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDwh.Models.Models;

public partial class FactSupportedCustomer
{
    public int SupportedCustomersId { get; set; }

    public int EmployeeId { get; set; }

    public int? TotalCustomers { get; set; }

    public string EmployeerName { get; set; }
}