// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LoadDwh.Models.Models;

public partial class FactSale
{
    public int OrderId { get; set; }

    public int EmployeeId { get; set; }

    public string CustomerId { get; set; }

    public int ShipperId { get; set; }

    public int ProductId { get; set; }

    public int DateId { get; set; }

    public decimal TotalSales { get; set; }

    public string Country { get; set; }

    public int QuantitySold { get; set; }
}